name: plotly-build-push
on:
  push:
    branches:
    - "*-release"
    - "main"
    - "gha-ci"

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.4
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - id: setup-pack
        uses: buildpacks/github-actions/setup-pack@v4.1.0
      - id: package
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          pack buildpack package --publish ${REPO}:${VERSION}
          echo "IMAGE_TAG=${REPO}:${VERSION}" >> "$GITHUB_OUTPUT"
        shell: bash
        env:
          REPO: quay.io/${{ github.repository_owner }}/apt-buildpack
          VERSION: ${{ steps.branch-name.outputs.current_branch }}-sha-${{ github.sha }}